#!/usr/bin/env python3
"""
Build app/embeddings.js — precomputed semantic embeddings for every prompt
in app/data.js, generated via the local OMLX embedding model.

Usage:
    python3 scripts/build_embeddings.py

Output:
    app/embeddings.js  ->  const galleryEmbeddings = [[...], ...];
    (aligned by index with galleryData in app/data.js)
"""
import json
import os
import re
import sys
import urllib.request

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FILE = os.path.join(BASE_DIR, 'app', 'data.js')
OUT_FILE = os.path.join(BASE_DIR, 'app', 'embeddings.js')
OMLX_URL = 'http://127.0.0.1:8000/v1/embeddings'
MODEL = 'Qwen3-Embedding-4B-4bit-DWQ'
BATCH_SIZE = 32
QUANT_BITS = 8  # quantize floats to int8 to shrink file size


def read_prompts():
    with open(DATA_FILE, 'r') as f:
        content = f.read()
    prompts = re.findall(r'"prompt": "([^"]+)"', content)
    if not prompts:
        sys.exit('No prompts found in ' + DATA_FILE)
    return prompts


def embed_batch(texts):
    body = json.dumps({'model': MODEL, 'input': texts}).encode('utf-8')
    req = urllib.request.Request(OMLX_URL, data=body, headers={'Content-Type': 'application/json'})
    with urllib.request.urlopen(req, timeout=120) as resp:
        data = json.loads(resp.read().decode('utf-8'))
    # data['data'] is a list of {index, embedding}
    ordered = [None] * len(texts)
    for item in data['data']:
        ordered[item['index']] = item['embedding']
    return ordered


def quantize(vec, bits=QUANT_BITS):
    """Quantize a float vector to int8 range [-127, 127] with a scale factor."""
    lo, hi = min(vec), max(vec)
    scale = (hi - lo) / 254.0 if hi > lo else 1.0
    q = [int(round((v - lo) / scale)) - 127 for v in vec]
    return q, lo, scale


def main():
    prompts = read_prompts()
    print(f'Embedding {len(prompts)} prompts via {MODEL}...')

    all_quantized = []
    all_offsets = []
    all_scales = []

    for start in range(0, len(prompts), BATCH_SIZE):
        batch = prompts[start:start + BATCH_SIZE]
        vecs = embed_batch(batch)
        for v in vecs:
            q, lo, scale = quantize(v)
            all_quantized.append(q)
            all_offsets.append(lo)
            all_scales.append(scale)
        print(f'  {min(start + BATCH_SIZE, len(prompts))}/{len(prompts)} done')

    # Write embeddings.js
    lines = ['// Auto-generated by scripts/build_embeddings.py — do not edit by hand.',
             '// Aligned by index with galleryData in app/data.js.',
             '// Each entry: { q: [int8...], lo: float, scale: float }',
             'const galleryEmbeddings = [']
    for q, lo, scale in zip(all_quantized, all_offsets, all_scales):
        lines.append('  {"q":[' + ','.join(str(x) for x in q) + '],"lo":' + repr(lo) + ',"scale":' + repr(scale) + '},')
    lines.append('];')
    lines.append('')

    with open(OUT_FILE, 'w') as f:
        f.write('\n'.join(lines))

    size_kb = os.path.getsize(OUT_FILE) / 1024
    print(f'Wrote {OUT_FILE} ({size_kb:.0f} KB, {len(all_quantized)} vectors)')


if __name__ == '__main__':
    main()